### ISSUE TITLE
Local backend not working for darwin-arm64 (macOS) - Command not found

### ISSUE THREAD

**Issue by sanjibukai** [woodpecker-ci/woodpecker#1378]
### Component

agent

#### Not possible to run bash commands with local backend for darwin-arm64
When running a job with simple bash commands on a macOS (with ARM64) with the local backend, `bash` throws an error about the command not being found.
Though, the log shows a gibberish text (seems to be a base64 text) instead of the actual command.

#### Example pipeline
Here is a very simple example:
```
platform: darwin/arm64
skip_clone: true

pipeline:
  test:
    image: bash
    commands:
      - uname -a
      - echo 'running test pipeline'
      - ls -al
```
#### Error
The following pipeline throw an error in the very first command with the following output:
```
bash: mlmIFsgLW4gIiRDSV9ORVRSQ19NQUNISU5FIiBdOyB0aGVuCmNhdCA8PEVPRiA+ICRIT01FLy5uZXRyYwptYWNoaW5lICRDSV9ORVRSQ19NQUNISU5FCmxvZ2luICRDSV9ORVRSQ19VU0VSTkFNRQpwYXNzd29yZCAkQ0lfTkVUUkNfUEFTU1dPUkQKRU9GCmNobW9kIDA2MDAgJEhPTUUvLm5ldHJjCmZpCnVuc2V0IENJX05FVFJDX1VTRVJOQU1FCnVuc2V0IENJX05FVFJDX1BBU1NXT1JECnVuc2V0IENJX1NDUklQVAoKZWNobyArICJlY2hvICdydW5uaW5nIHRlc3QgcGlwZWxpbmUnIgplY2hvICdydW5uaW5nIHRlc3QgcGlwZWxpbmUnCgplY2hvICsgImxzIC1hbCIKbHMgLWFsCgplY2hvICsgInRvdWNoIHRvdWNoX2Zvcl9kdSIKdG91Y2ggdG91Y2hfZm9yX2R1CgplY2hvICsgImR1IC1zaCAqIgpkdSAtc2ggKgoK: command not found
```

### System Info

Woodpecker `next` version is used and according to the logs at startup, both the server and the  agent are running `next-b15ca52a` (latest version at the time of writing).
The agent version  is compiled from source directly on the mac machine using the following command:
`TARGETOS=darwin TARGETARCH=arm64 make build-agent`.

### Additional context

Here is the output of the agent running with `trace` log level, if it can help:
```
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","time":"2022-10-31T14:34:18+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:101","message":"received execution"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","time":"2022-10-31T14:34:18+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:115","message":"listen for cancel signal"}
{"level":"debug","ID":"1532","Repo":"aaa/mac_local_test","Pipeline":"42","time":"2022-10-31T14:34:18+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:73","message":"Executing 3 stages, in order of:"}
{"level":"debug","ID":"1532","Repo":"aaa/mac_local_test","Pipeline":"42","Stage":"wp_0_7811566641196302698_stage_0","Steps":"wp_0_7811566641196302698_step_0","time":"2022-10-31T14:34:18+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:83","message":"stage"}
{"level":"debug","ID":"1532","Repo":"aaa/mac_local_test","Pipeline":"42","Stage":"wp_0_7811566641196302698_stage_1","Steps":"wp_0_7811566641196302698_step_1","time":"2022-10-31T14:34:18+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:83","message":"stage"}
{"level":"debug","ID":"1532","Repo":"aaa/mac_local_test","Pipeline":"42","Stage":"wp_0_7811566641196302698_stage_2","Steps":"wp_0_7811566641196302698_step_2","time":"2022-10-31T14:34:18+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:83","message":"stage"}
{"level":"debug","ID":"1532","Repo":"aaa/mac_local_test","Pipeline":"42","Step":"wp_0_7811566641196302698_step_0","time":"2022-10-31T14:34:18+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:155","message":"Prepare"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","image":"bash","stage":"download","exit_code":0,"exited":false,"time":"2022-10-31T14:34:18+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:273","message":"update step status"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","image":"bash","stage":"download","exit_code":0,"exited":false,"time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:281","message":"update step status complete"}
{"level":"debug","ID":"1532","Repo":"aaa/mac_local_test","Pipeline":"42","Step":"wp_0_7811566641196302698_step_0","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:179","message":"Executing"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","image":"bash","stage":"download","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:172","message":"log stream opened"}
{"level":"trace","name":"download","ID":"1532","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/rpc/line.go:69","message":"grpc write line: bash: mlmIFsgLW4gIiRDSV9ORVRSQ19NQUNISU5FIiBdOyB0aGVuCmNhdCA8PEVPRiA+ICRIT01FLy5uZXRyYwptYWNoaW5lICRDSV9ORVRSQ19NQUNISU5FCmxvZ2luICRDSV9ORVRSQ19VU0VSTkFNRQpwYXNzd29yZCAkQ0lfTkVUUkNfUEFTU1dPUkQKRU9GCmNobW9kIDA2MDAgJEhPTUUvLm5ldHJjCmZpCnVuc2V0IENJX05FVFJDX1VTRVJOQU1FCnVuc2V0IENJX05FVFJDX1BBU1NXT1JECnVuc2V0IENJX1NDUklQVAoKZWNobyArICJ1bmFtZSAtYSIKdW5hbWUgLWEKCmVjaG8gKyAiZWNobyAncnVubmluZyBsb2NhbCBiYWNrZW5kIHRlc3QgcGlwZWxpbmUnIgplY2hvICdydW5uaW5nIGxvY2FsIGJhY2tlbmQgdGVzdCBwaXBlbGluZScKCmVjaG8gKyAibHMgLWFsIgpscyAtYWwKCmVjaG8gKyAidG91Y2ggdG91Y2hfZm9yX2R1Igp0b3VjaCB0b3VjaF9mb3JfZHUKCmVjaG8gKyAiZHUgLXNoICoiCmR1IC1zaCAqCgo=: command not found\n"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","image":"bash","stage":"download","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:180","message":"log stream copied"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","image":"bash","stage":"download","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:196","message":"log stream uploading"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","image":"bash","stage":"download","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:200","message":"log stream upload complete"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","image":"bash","stage":"download","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:204","message":"log stream closed"}
{"level":"debug","ID":"1532","Repo":"aaa/mac_local_test","Pipeline":"42","Step":"wp_0_7811566641196302698_step_0","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:185","message":"Complete"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","image":"bash","stage":"download","exit_code":127,"exited":true,"time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:273","message":"update step status"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","image":"bash","stage":"download","exit_code":127,"exited":true,"time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:281","message":"update step status complete"}
{"level":"debug","ID":"1532","Repo":"aaa/mac_local_test","Pipeline":"42","Step":"wp_0_7811566641196302698_step_1","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:155","message":"Prepare"}
{"level":"debug","ID":"1532","Repo":"aaa/mac_local_test","Pipeline":"42","Step":"wp_0_7811566641196302698_step_1","error":"wp_0_7811566641196302698_step_0 : exit code 127","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:162","message":"Skipped due to OnFailure=false"}
{"level":"debug","Pipeline":"42","ID":"1532","Repo":"aaa/mac_local_test","Step":"wp_0_7811566641196302698_step_2","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:155","message":"Prepare"}
{"level":"debug","Pipeline":"42","ID":"1532","Repo":"aaa/mac_local_test","Step":"wp_0_7811566641196302698_step_2","error":"wp_0_7811566641196302698_step_0 : exit code 127","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/pipeline.go:162","message":"Skipped due to OnFailure=false"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","error":"","exit_code":127,"time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:352","message":"pipeline complete"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:354","message":"uploading logs"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:358","message":"uploading logs complete"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","error":"","exit_code":127,"time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:363","message":"updating pipeline status"}
{"level":"error","error":"rpc error: code = Unknown desc = Step finished with exitcode 127, ","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/pipeline/rpc/client_grpc.go:97","message":"grpc error: wait(): code: Unknown: rpc error: code = Unknown desc = Step finished with exitcode 127, "}
{"level":"warn","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","error":"rpc error: code = Unknown desc = Step finished with exitcode 127, ","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:119","message":"cancel signal received"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:131","message":"pipeline done"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"42","id":"1532","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:369","message":"updating pipeline status complete"}
{"level":"debug","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/cmd/agent/agent.go:172","message":"polling new steps"}
{"level":"debug","time":"2022-10-31T14:34:19+01:00","caller":"/Users/aaa/woodpecker-agent/source/woodpecker/agent/runner.go:65","message":"request next execution"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by sanjibukai** [comment]
Hello everybody!
I tried to run the exact same pipeline with an older version (I arbitrarily chose commit [62d8276](https://github.com/woodpecker-ci/woodpecker/commit/62d82765fd5d783ef8597ec3ce75263741cd0eaa) since it was something like a month ago when I remember I was able to execute jobs with local backend on a mac).
And it worked!
My server is running using the docker image and the agent the `darwin-arm64` binary. I build both of these artifacts from the same commit hash.
I verified that when the server and the agent starts up, they correctly log they are started with version `next-62d82765`.

So I guess there is some regression bug that is introduced since then.
I'm willing to try a bunch of versions (using dichotomy).. But I'd like to receive a few hints about which part of the codebase can be correlated so that I only look at commits that edited those parts..

**Comment by sanjibukai** [comment]
I just tried with the latest build for the agent (still using the older server).. And the issue came back!
So it seems only related to the agent!

**Comment by sanjibukai** [comment]
I may have found something interesting @6543 
The agent starts throwing the error in that very commit https://github.com/woodpecker-ci/woodpecker/commit/b15ca52a638ecfb533512a453d096b5451d2fe89
After that one it doesn't work..
In the previous commit (e61f97f) it's working.

**Comment by sanjibukai** [comment]
BTW that was working with an older version of the server as well..
With the latest server, at that commit b15ca52 it's still doing what explained in the issue description.
But with the previous agent (e61f97f) the agent is crashing with the following error:
```
{"level":"info","time":"2022-11-01T17:47:00+01:00","caller":"/Users/aaa/woodpecker/cmd/agent/agent.go:181","message":"Starting Woodpecker agent with version 'next-e61f97f8' and backend 'local' running up to 1 pipelines in parallel"}
{"level":"debug","time":"2022-11-01T17:47:00+01:00","caller":"/Users/aaa/woodpecker/cmd/agent/agent.go:165","message":"loaded local backend engine"}
{"level":"debug","time":"2022-11-01T17:47:00+01:00","caller":"/Users/aaa/woodpecker/cmd/agent/agent.go:172","message":"polling new steps"}
{"level":"debug","time":"2022-11-01T17:47:00+01:00","caller":"/Users/aaa/woodpecker/agent/runner.go:65","message":"request next execution"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"56","id":"1770","time":"2022-11-01T17:47:06+01:00","caller":"/Users/aaa/woodpecker/agent/runner.go:101","message":"received execution"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"56","id":"1770","time":"2022-11-01T17:47:06+01:00","caller":"/Users/aaa/woodpecker/agent/runner.go:115","message":"listen for cancel signal"}
{"level":"debug","ID":"1770","Repo":"aaa/mac_local_test","Pipeline":"56","time":"2022-11-01T17:47:06+01:00","caller":"/Users/aaa/woodpecker/pipeline/pipeline.go:73","message":"Executing 3 stages, in order of:"}
{"level":"debug","ID":"1770","Repo":"aaa/mac_local_test","Pipeline":"56","Stage":"wp_0_7937012288822635375_stage_0","Steps":"wp_0_7937012288822635375_step_0","time":"2022-11-01T17:47:06+01:00","caller":"/Users/aaa/woodpecker/pipeline/pipeline.go:83","message":"stage"}
{"level":"debug","ID":"1770","Repo":"aaa/mac_local_test","Pipeline":"56","Stage":"wp_0_7937012288822635375_stage_1","Steps":"wp_0_7937012288822635375_step_1","time":"2022-11-01T17:47:06+01:00","caller":"/Users/aaa/woodpecker/pipeline/pipeline.go:83","message":"stage"}
{"level":"debug","ID":"1770","Repo":"aaa/mac_local_test","Pipeline":"56","Stage":"wp_0_7937012288822635375_stage_2","Steps":"wp_0_7937012288822635375_step_2","time":"2022-11-01T17:47:06+01:00","caller":"/Users/aaa/woodpecker/pipeline/pipeline.go:83","message":"stage"}
{"level":"debug","ID":"1770","Repo":"aaa/mac_local_test","Pipeline":"56","Step":"wp_0_7937012288822635375_step_0","time":"2022-11-01T17:47:06+01:00","caller":"/Users/aaa/woodpecker/pipeline/pipeline.go:155","message":"Prepare"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"56","id":"1770","image":"bash","stage":"download","exit_code":0,"exited":false,"time":"2022-11-01T17:47:06+01:00","caller":"/Users/aaa/woodpecker/agent/runner.go:273","message":"update step status"}
{"level":"debug","repo":"aaa/mac_local_test","pipeline":"56","id":"1770","image":"bash","stage":"download","exit_code":0,"exited":false,"time":"2022-11-01T17:47:06+01:00","caller":"/Users/aaa/woodpecker/agent/runner.go:281","message":"update step status complete"}
{"level":"debug","ID":"1770","Repo":"aaa/mac_local_test","Pipeline":"56","Step":"wp_0_7937012288822635375_step_0","time":"2022-11-01T17:47:06+01:00","caller":"/Users/aaa/woodpecker/pipeline/pipeline.go:179","message":"Executing"}
panic: runtime error: slice bounds out of range [1:0]

goroutine 53 [running]:
github.com/woodpecker-ci/woodpecker/pipeline/backend/local.(*local).Exec(0x1400030e450, {0x106709f78?, 0x140005d0980}, 0x14000192f00)
	/Users/aaa/woodpecker/pipeline/backend/local/local.go:85 +0x860
github.com/woodpecker-ci/woodpecker/pipeline.(*Runtime).exec(0x140002c4620, 0x14000192f00)
	/Users/aaa/woodpecker/pipeline/pipeline.go:209 +0x44
github.com/woodpecker-ci/woodpecker/pipeline.(*Runtime).execAll.func1()
	/Users/aaa/woodpecker/pipeline/pipeline.go:181 +0x1b8
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/aaa/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/aaa/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa4
```
I guess that this is an expected behavior if there's a mismatched between the server and the agent maybe?

**Comment by sanjibukai** [comment]
Ok I just tried running same versions for the server and agent..
- `next-e61f97f` => Bash commands work
- `next-b15ca52` => Bash commands do NOT work (and agent is not crashing)

**Comment by 6543** [comment]
@sanjibukai #1395 I think it was catched ... can you check?

**Comment by sanjibukai** [comment]
Cool!
It's working again!
I just tested with the latest `next` which happen to be `next-e90f605` and the commands are working!
Closing the ticket!
