### ISSUE TITLE
Org settings not loading anymore

### ISSUE THREAD

**Issue by anbraten** [woodpecker-ci/woodpecker#3975]
If I try to open the settings of some org like https://ci.woodpecker-ci.org/orgs/2/settings

I only get:

```
Error: Please use this "useTabsClient" composition inside a component running "useTabsProvider".
    at D (TextField.vue_vue_type_script_setup_true_lang-B4Ni6bSv.js:1:475)
    at setup (Tab.vue_vue_type_script_setup_true_lang-i5tNtmC3.js:1:1449)
    at oa (index-DBHkDads.js:14:38)
    at _p (index-DBHkDads.js:14:38907)
    at pp (index-DBHkDads.js:14:38690)
    at B (index-DBHkDads.js:14:22544)
    at K (index-DBHkDads.js:14:22436)
    at b (index-DBHkDads.js:14:19361)
    at E (index-DBHkDads.js:14:20776)
    at c (index-DBHkDads.js:14:20120)
```

**Comment by mkobel** [comment]
Are there any plans to backport/release the fix #4002 before the 3.0.0 release?
