### ISSUE TITLE
woodpecker-next error: `panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by dessalines** [woodpecker-ci/woodpecker#4652]
### Component

agent

### Describe the bug

I'm getting this error for the woodpecker-next agent today:

```
woodpecker-agent-1  | {"level":"info","time":"2024-12-31T16:38:42Z","message":"log level: info"}
woodpecker-agent-1  | {"level":"info","time":"2024-12-31T16:38:42Z","message":"starting Woodpecker agent with version 'next-5b0d788737' and backend 'docker' using platform 'linux/amd64' running up to 1 pipelines in parallel"}
woodpecker-agent-1  | panic: runtime error: invalid memory address or nil pointer dereference
woodpecker-agent-1  | 	panic: runtime error: invalid memory address or nil pointer dereference
woodpecker-agent-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa8413f]
woodpecker-agent-1  | 
woodpecker-agent-1  | goroutine 74 [running]:
woodpecker-agent-1  | go.woodpecker-ci.org/woodpecker/v3/pipeline/backend/docker.(*docker).DestroyWorkflow(0x34358a0, {0x231b610, 0xc000469630}, 0xc000018b00, {0xc00052c635, 0x5})
woodpecker-agent-1  | 	/src/pipeline/backend/docker/docker.go:326 +0xff
woodpecker-agent-1  | go.woodpecker-ci.org/woodpecker/v3/pipeline.(*Runtime).Run.func1()
woodpecker-agent-1  | 	/src/pipeline/pipeline.go:112 +0x7f
woodpecker-agent-1  | panic({0x1cde8e0?, 0x33f99f0?})
woodpecker-agent-1  | 	/usr/local/go/src/runtime/panic.go:785 +0x132
woodpecker-agent-1  | go.woodpecker-ci.org/woodpecker/v3/pipeline/backend/docker.(*docker).SetupWorkflow(0x34358a0, {0x231b610, 0xc000469630}, 0xc000018b00, {0xc00052c635, 0x5})
woodpecker-agent-1  | 	/src/pipeline/backend/docker/docker.go:148 +0xf5
woodpecker-agent-1  | go.woodpecker-ci.org/woodpecker/v3/pipeline.(*Runtime).Run(0xc0002389a0, {0x231b610, 0xc000469630})
woodpecker-agent-1  | 	/src/pipeline/pipeline.go:118 +0x31b
woodpecker-agent-1  | go.woodpecker-ci.org/woodpecker/v3/agent.(*Runner).Run(0xc000018a00, {0x231b610, 0xc000469630}, {0x231b5a0, 0x3456900})
woodpecker-agent-1  | 	/src/agent/runner.go:153 +0xeef
woodpecker-agent-1  | go.woodpecker-ci.org/woodpecker/v3/cmd/agent/core.run.func5()
woodpecker-agent-1  | 	/src/cmd/agent/core/agent.go:293 +0x205
woodpecker-agent-1  | golang.org/x/sync/errgroup.(*Group).Go.func1()
woodpecker-agent-1  | 	/src/vendor/golang.org/x/sync/errgroup/errgroup.go:78 +0x50
woodpecker-agent-1  | created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
woodpecker-agent-1  | 	/src/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0x96
woodpecker-agent-1  | {"level":"info","time":"2024-12-31T16:38:44Z","message":"log level: info"}
woodpecker-agent-1  | {"level":"info","time":"2024-12-31T16:38:45Z","message":"starting Woodpecker agent with version 'next-5b0d788737' and backend 'docker' using platform 'linux/amd64' running up to 1 pipelines in parallel"}
```

### Steps to reproduce

Install woodpecker-agent:next

### System Info

```shell
Agent error: image is : `21f2e0733e93`
```

### Additional context

NA

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

**Comment by dessalines** [comment]
Seems to have resolved itself with newer versions of next. Sry!
