### ISSUE TITLE
Server panic after signal SIGTERM

### ISSUE THREAD

**Issue by 6543** [woodpecker-ci/woodpecker#471]
version: latest

When sending a sigterm to the runner with `sudo docker kill woodpecker --signal=SIGTERM`, the runner gracefully shutsdown, but the server panics

```
panic: Write called after Handler finished

goroutine 29210 [running]:
net/http.(*http2responseWriter).write(0xc000012828, 0x18, 0x0, 0x0, 0x0, 0x11009c2, 0x18, 0x1045f60, 0x7f359512c401, 0x7f359512c460)
        /usr/local/go/src/net/http/h2_bundle.go:6256 +0x1f7
net/http.(*http2responseWriter).WriteString(0xc000012828, 0x11009c2, 0x18, 0x7f359512c460, 0xc000012828, 0x7f359512c401)
        /usr/local/go/src/net/http/h2_bundle.go:6249 +0x55
io.WriteString(0x7f359512c440, 0xc000012828, 0x11009c2, 0x18, 0xc000012828, 0x7f3595967101, 0x7f359512c420)
        /usr/local/go/src/io/io.go:309 +0x74
github.com/gin-gonic/gin.(*responseWriter).WriteString(0xc0002f9500, 0x11009c2, 0x18, 0x7f359512c420, 0xc0002f9500, 0xc001807e01)
        /drone/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/response_writer.go:85 +0x7a
io.WriteString(0x7f3595967170, 0xc0002f9500, 0x11009c2, 0x18, 0xc0002f9500, 0xc0000797c0, 0x0)
        /usr/local/go/src/io/io.go:309 +0x74
github.com/woodpecker-ci/woodpecker/server/api.LogStreamSSE.func2(0x12dfdd0, 0xc0003b8180, 0xc0015dbad0, 0xc000edee40, 0x12e9e58, 0xc0002f9500, 0xc0016111b0)
        /drone/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:207 +0x168
created by github.com/woodpecker-ci/woodpecker/server/api.LogStreamSSE
        /drone/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:191 +0x699
```

**Comment by 6543** [comment]
not a problem anymore ... - i guess #514 did the job

**Comment by isuruf** [comment]
Thanks @6543

**Comment by 6543** [comment]
@isuruf if you see it out in the wild again - please reopen a new issue :)

keep clam and report bugs :bug: :+1:
