### ISSUE TITLE
Server panic when closing log window of a running pipeline

### ISSUE THREAD

**Issue by fblaese** [woodpecker-ci/woodpecker#850]
### Component

server, web-ui

### Describe the bug

When exiting the log view of an active pipeline, the server panics with the following message:

```
panic: Write called after Handler finished
goroutine 778 [running]:
net/http.(*http2responseWriter).write(0xc000010068, 0x18, 0x0, 0x0, 0x0, 0x1252ef6, 0x18, 0x1179f20, 0x7f169831f101, 0x7f169831f200)
        /usr/local/go/src/net/http/h2_bundle.go:6364 +0x1f7
net/http.(*http2responseWriter).WriteString(0xc000010068, 0x1252ef6, 0x18, 0x7f169831f200, 0xc000010068, 0x7f169831f101)
        /usr/local/go/src/net/http/h2_bundle.go:6357 +0x55
io.WriteString(0x7f169831f1e0, 0xc000010068, 0x1252ef6, 0x18, 0xc000010068, 0x7f169831f101, 0x7f169831f1c0)
        /usr/local/go/src/io/io.go:309 +0x74
github.com/gin-gonic/gin.(*responseWriter).WriteString(0xc000a8e400, 0x1252ef6, 0x18, 0x7f169831f1c0, 0xc000a8e400, 0xc0000a8101)
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/response_writer.go:85 +0x7a
io.WriteString(0x7f169831f1a0, 0xc000a8e400, 0x1252ef6, 0x18, 0xc000a8e400, 0xc000118a00, 0x0)
        /usr/local/go/src/io/io.go:309 +0x74
github.com/woodpecker-ci/woodpecker/server/api.LogStreamSSE.func2(0x1429690, 0xc000724200, 0xc00052ee70, 0xc000620600, 0x1434af8, 0xc000a8e400, 0xc00060a0d0)
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:199 +0x185
created by github.com/woodpecker-ci/woodpecker/server/api.LogStreamSSE
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:179 +0x6f9
```

### System Info

```shell
woodpecker: 0.15.0
Chromium: 99.0.4844.82
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

**Comment by fblaese** [comment]
Interestingly enough, this only happens with TLS (using let's encrypt) is enabled via `WOODPECKER_LETS_ENCRYPT=true`

**Comment by 6543** [comment]
ok so we have to priorize #360 as bugfix too ...

**Comment by adasauce** [comment]
Is there a workaround to this in the short term without disabling TLS? Is it avoided by just not watching the log output?
